version: '3.8'

services:
  web:
    build: .
    container_name: camagru_web
    ports:
      - "8000:80"
    volumes:
      - ./app/public:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: camagru_db
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
